### ISSUE TITLE
Crash with Archbows mod, i think

### ISSUE THREAD

**Issue by qVoidreaver** [Sonnenlicht-as/Trajectory-Estimation#2]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Trajectory Estimation (trajectory_estimation), Version: 1.0.2-1.18.2
		Issue tracker URL: https://github.com/Sonnenlicht-as/Trajectory-Estimation/issues
		at TRANSFORMER/trajectory_estimation@1.0.2-1.18.2/sonnenlichts.tje.client.extra.ArchBowsExtra.isFlatBowItem(ArchBowsExtra.java:15)
Stacktrace:
	at sonnenlichts.tje.client.extra.ArchBowsExtra.isFlatBowItem(ArchBowsExtra.java:15) ~[trajectory_estimation-1.0.2-1.18.2.jar%23359!/:1.0.2-1.18.2] {re:classloading}
	at sonnenlichts.tje.client.event.ClientRenderHandler.rendersWorldEvent(ClientRenderHandler.java:468) ~[trajectory_estimation-1.0.2-1.18.2.jar%23359!/:1.0.2-1.18.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_2111_ClientRenderHandler_rendersWorldEvent_RenderLevelStageEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderStage(ForgeHooksClient.java:238) ~[forge-1.18.2-40.2.17-universal.jar%23404!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1371) ~[client-1.18.2-20220404.173914-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%23399!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:epicacg.mixins.json:MixinGameRenderer,pl:mixin:APP:zume-lexforge18.mixins.json:GameRendererMixin,pl:mixin:APP:dynamic_fps.mixins.json:GameRendererMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.compat1192minus.GameRendererMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin,pl:mixin:APP:mixins.satin.client.json:event.GameRendererMixin,pl:mixin:APP:weaponleveling-common.mixins.json:client.MixinGameRenderer,pl:mixin:APP:lodestone.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by qVoidreaver** [comment]
New version**

**Comment by Sonnenlicht-as** [comment]
Thanks for your feedback. Can you provide more information, such as loading other mods? And plz provide a more complete crash log.

**Comment by qVoidreaver** [comment]
[crash-2024-03-05_13.37.15-client.txt](https://github.com/Sonnenlicht-as/Trajectory-Estimation/files/14504181/crash-2024-03-05_13.37.15-client.txt)

 This file would be the complete crash log. I don't know if you wanted to know about the other added compatibilities, but I don't think I can provide information like that. I'm currently using "Arch Bows" and "Archers Arsenal" (which were the ones implemented in this new version), and apparently the error only occurs with Arch

**Comment by qVoidreaver** [comment]
Oh, and by the way, without wanting to give you more work hahaha, but there are a lot of throwing weapons in the "brass_armory" mod, if you could add them to your list of future implementations, I'd appreciate it. And there's also a single bow in the "aquaculture 2" mod. 

 And once again, thank you for your attention and the dedication of your time to this mod.

**Comment by Sonnenlicht-as** [comment]
OK, they will all be added in the next version. In addition, the reason for the error is a version issue with archbows. The package structure of archbows code below 1.0.8 and above 1.0.8 is different, resulting in NoClassDefFoundError. 
So, plz download versions 1.0.8-1.18.2 and above of archbows. 
versions 1.0.9-1.18.2: https://www.curseforge.com/minecraft/mc-mods/arch-bows/files/4704699

**Comment by qVoidreaver** [comment]
Oh, my bad, I have so many mods that I didn't realize that this one has been updated for a year lmao. Thanks!
